apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  nodeSelector:
    role: backend
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: wkwtfigo/backend-service:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-logs
          mountPath: /app/.logs
      volumes:
      - name: app-logs
        hostPath:
          path: /var/log/app-redirect-balancer
          type: DirectoryOrCreate