apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
    spec:
      nodeSelector:
        role: balancer
      containers:
      - name: loadbalancer
        image: wkwtfigo/load-balancer:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: app-logs
          mountPath: /app/.logs
      volumes:
      - name: app-logs
        hostPath:
          path: /var/log/app-redirect-balancer
          type: DirectoryOrCreate
