apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  labels:
    app: wazuh
spec:
  selector:
    matchLabels:
      app: wazuh
  template:
    metadata:
      labels:
        app: wazuh
    spec:
      containers:
      - name: wazuh-agent
        image: wazuh/wazuh-agent:4.7.0
        env:
        - name: MANAGER_IP
          valueFrom:
            secretKeyRef:
              name: wazuh-secrets
              key: WAZUH_MANAGER_IP
        - name: REGISTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wazuh-secrets
              key: AGENT_REG_PASSWORD
        securityContext:
          privileged: true
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
