name: CI/CD Pipeline

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-test-lint-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r balanced_instance/requirements.txt
                  pip install autopep8 pytest-asyncio httpx
                  pip install pytest-mock

            - name: Run autopep8 check
              run: |
                  autopep8 --in-place --recursive --aggressive --aggressive .

            - name: Run specific test file
              run: |
                  PYTHONPATH=$PYTHONPATH:. pytest tests/test_app1.py -v
                  PYTHONPATH=$PYTHONPATH:. pytest tests/test_app2.py -v