name: CI/CD Pipeline

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-test:
        runs-on: ubuntu-latest
        services:
          docker:
            image: docker:24-dind
            options: --privileged
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r balanced_instance/requirements.txt
                  pip install -r balancer_server/requirements.txt
                  pip install autopep8 pytest-asyncio httpx pytest-mock

            - name: Run autopep8 check
              run: |
                  autopep8 --in-place --recursive --aggressive --aggressive .

            - name: Run specific test file
              run: |
                  PYTHONPATH=$PYTHONPATH:. pytest tests/test_app1.py -v

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
      
            - name: Build and push backend-service image
              uses: docker/build-push-action@v5
              with:
                context: balanced_instance
                file: balanced_instance/Dockerfile
                push: false
                load: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-service:latest
      
            - name: Build and push load-balancer image
              uses: docker/build-push-action@v5
              with:
                context: balancer_server
                file: balancer_server/Dockerfile
                push: false
                load: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/load-balancer:latest

            - name: Run backend container
              run: |
                docker run -d --name backend1 -p 8888:8888 -p 8080:8080 backend-service

            - name: Run backend container
              run: |
                 docker run -d --name load-balancer -p 8000:8000 -p 8001:8001 load-balancer 
      
            - name: Install ApacheBench
              run: |
                sudo apt-get update
                sudo apt-get install -y apache2-utils

            - name: Run load test with ApacheBench
              run: |
                ab -n 1000 -c 10 http://localhost:8000/your-endpoint